text = {"Megérkezel a kazamata bejáratához. Csikorogva kinyílik az ajtó és egy sötét, dohos folyosó fogad.": "You arrive at the entrance to the kazamata. The door creaks open and you are greeted by a dark, musty corridor.",
        "belépsz és gyyújtasz egy fáklyát": "you enter and light a torch",
        "besétálsz a sötétbe": "you walk into the dark",
        "Túl hideg van, halálra fagytál!": "It's too cold, you're freezing to death",
        "újrakezdés": "Restart",
        "kilépés": "exit",
        "Gyújtasz egy fáklyát. Balra van egy nyitott ajtó, de a fény nem hatol be. Jobbra egy zárt, rozoga ajtó.": "You light a torch. To the left is an open door, but the light does not enter. To the right is a closed, rickety door.",
        "Jobb oldali ajtó": "Door on the right",
        "Bal oldali ajtó": "Left door",
        #Left door
        "Besétálsz a nyitott szobába, a fáklyád nem ér semmit, ezért nem látsz és belesétálsz egy medvecsapdába.": "You walk into the open room, your torch is useless, so you can't see and you walk into a bear trap.",
        #Right door
        "Megpróbálod kinyitni az ajtó. Nincs zárva, ezért lassan csikorogva kinyílik. Egy kobold van a szobában.": "You try to open the door. It's not locked, so it slowly creaks open. There is a leprechaun in the room",
        "harc! (könnyű)": "fight! (easy)",
        "menekülés": "escape",
        "Gyáván megfutamodtál. A játék véget ért!": "You've run away like a coward. The game is over!",
        "Nagyobbat dobtál mint az ellenfél, ezért csúnyán megverted!": "You threw bigger than the opponent, so you beat him badly!",
        "kifosztod": "loot him",
        "átvizsgálod a szobá": "you search the room",
        "Kevesebbet dobtál mint az ellenfél, ezért csúnyán megvert! Meghaltál!": "You threw less than the opponent, so he beat you badly! You died!",
        "Átkutatod a koboldot. Találsz nála egy rozsdás kenőkést, és egy félig megevett zsíroskerenyeret. A rozsdás kenőkés szerencsét hoz!": "You search the leprechaun. You will find a rusty grease knife and a half-eaten greasy scissors. The rusty grease knife brings luck!",
        "átvizsgálod a szobát": "you search the room",
        "visszamész a folysóra": "you're going back to the folysore",
        "A folysó továbbra is üres. Most megfigyeled a végét, és látod hogy nincs folytatása.": "The folysore is still empty. Now you observe the end and see that there is no continuation.",
        "vissza a szobába": "back to the room",
        "A szobát bevilágítja a fáklyád. Van bent egy asztal, és pár szék. Előtted és jobbról is egy ajtó van.": "The room is lit by your torch. There is a table and some chairs. There's a door in front of you and to the right.",        
        "Előttem lévő ajtó kinyitása": "Open the door in front of me",
        "jobb oldali ajtó kinyitása": "Open the door on the right",
        "Odasétálsz az ajtóhoz, és szerencsédre nyitva van": "You walk up to the door and it's open, lucky for you",
        "bemész": "you go in",
        "másik ajtó megnézése": "check another door",
        "A jobb oldali ajtó zárva van. Lehetetlen kinyitni.": "The door on the right is locked. Your unable to open it.",
        "vissza a másikhoz": "back to other",
        "Besétálsz az ajtón, és látsz egy kijáratot, fény szűrődik onnan. De egy hatalmas ork állja az utad.": "You walk through the door and see an exit, light filters out. But a huge orc stands in your way."
        "Harcolsz vele(nehéz)": "You fight it (hard)",
        "megpróbálod megkerülni": "you try to go around it",
        "megpróltál elfutni az ork mellett, és nagy szerencsédre sikkerel jártál és kijutottál a kazamatából": "you tried to run past the orc, and lucky for you, you got out of the orc's casemate in a chic way",
        "játék újrakezdése": "restart the game",
        "kilépés": "exit",
        "Nagyobbat dobtál mint az ellenfél, ezért legyőzted és végre kijutottál a kazamatából": "You rolled higher than your opponent, so you beat him and finally got out of the kazamata",
        "Kevesebbet dobtál mint az ellenfél, ezért csúnyán elfenekelt! Meghaltál!": "You rolled less than your opponent, so he spanked you badly! You died!",
        }
