text = {"Megérkezel a kazamata bejáratához. Csikorogva kinyílik az ajtó és egy sötét, dohos folyosó fogad.": "Вы подходите к входу в казарму. Дверь со скрипом открывается, и вас встречает темный, затхлый коридор",
        "belépsz és gyyújtasz egy fáklyát": "Вы входите и зажигаете факел",
        "besétálsz a sötétbe": "вы идете в темноте",
        "Túl hideg van, halálra fagytál!": "Слишком холодно, ты замерзнешь насмерть",
        "újrakezdés": "Перезагрузка",
        "kilépés": "выход",
        "Gyújtasz egy fáklyát. Balra van egy nyitott ajtó, de a fény nem hatol be. Jobbra egy zárt, rozoga ajtó.": "Вы зажигаете факел. Слева - открытая дверь, но свет не проникает. Справа - закрытая, шаткая дверь",
        "Jobb oldali ajtó": "Дверь справа",
        "Bal oldali ajtó": "Левая дверь",
        #Левая дверь
        "Besétálsz a nyitott szobába, a fáklyád nem ér semmit, ezért nem látsz és belesétálsz egy medvecsapdába.": "Вы входите в открытую комнату, ваш фонарь бесполезен, поэтому вы ничего не видите и попадаете в медвежий капкан",
        #Правая дверь
        "Megpróbálod kinyitni az ajtó. Nincs zárva, ezért lassan csikorogva kinyílik. Egy kobold van a szobában.": "Вы пытаетесь открыть дверь. Она не заперта, поэтому медленно со скрипом открывается. В комнате находится лепрекон",
        "harc! (könnyű)": "сражайся! (легко)",
        "menekülés": "побег",
        "Gyáván megfutamodtál. A játék véget ért!": "Ты убежал как трус. Игра окончена!",
        "Nagyobbat dobtál mint az ellenfél, ezért csúnyán megverted!": "Ты бросил больше, чем соперник, поэтому ты его сильно побил!",
        "kifosztod": "разграбить его",
        "átvizsgálod a szobá": "вы обыскиваете комнату",
        "Kevesebbet dobtál mint az ellenfél, ezért csúnyán megvert! Meghaltál!": "Ты бросил меньше, чем противник, поэтому он сильно побил тебя! Ты умер!",
        "Átkutatod a koboldot. Találsz nála egy rozsdás kenőkést, és egy félig megevett zsíroskerenyeret. A rozsdás kenőkés szerencsét hoz!": "Ищите лепрекона. Вы найдете ржавый нож для смазки и полусъеденные сальные ножницы. Ржавый нож для смазки приносит удачу!",
        "átvizsgálod a szobát": "вы обыскиваете комнату",
        "visszamész a folysóra": "вы возвращаетесь в фолисору",
        "A folysó továbbra is üres. Most megfigyeled a végét, és látod hogy nincs folytatása.": "Фолисор все еще пуст. Теперь вы наблюдаете конец и видите, что продолжения нет",
        "vissza a szobába": "вернуться в комнату",
        "A szobát bevilágítja a fáklyád. Van bent egy asztal, és pár szék. Előtted és jobbról is egy ajtó van.": "Комната освещена вашим факелом. Здесь есть стол и несколько стульев. Перед вами и справа есть дверь",        
        "Előttem lévő ajtó kinyitása": "Откройте дверь передо мной",
        "Jobb oldali ajtó kinyitása": "Откройте дверь справа",
        "Odasétálsz az ajtóhoz, és szerencsédre nyitva van": "Вы подходите к двери, а она открыта, к счастью для вас",
        "bemész": "вы входите",
        "másik ajtó megnézése": "проверьте другую дверь",
        "A jobb oldali ajtó zárva van. Lehetetlen kinyitni.": "Дверь справа заперта. Вы не можете ее открыть",
        "vissza a másikhoz": "назад к другому",
        "Besétálsz az ajtón, és látsz egy kijáratot, fény szűrődik onnan. De egy hatalmas ork állja az utad.": "Вы проходите через дверь и видите выход, свет фильтруется. Но на вашем пути стоит огромный орк".
        "Harcolsz vele(nehéz)": "Вы сражаетесь с ним (упорно)",
        "megpróbálod megkerülni": "вы пытаетесь его обойти",
        "megpróltál elfutni az ork mellett, és nagy szerencsédre sikkerel jártál és kijutottál a kazamatából": "ты попытался пробежать мимо орка, и, к счастью для тебя, ты шикарно выбрался из каземата орка",
        "játék újrakezdése": "перезапустить игру",
        "kilépés": "exit",
        "Nagyobbat dobtál mint az ellenfél, ezért legyőzted és végre kijutottál a kazamatából": "Вы сделали бросок выше, чем ваш противник, поэтому вы победили его и наконец-то вышли из казаматы",
        "Kevesebbet dobtál mint az ellenfél, ezért csúnyán elfenekelt! Meghaltál!": "Вы бросили меньше, чем ваш противник, поэтому он сильно отшлепал вас! Вы умерли!",
        }
